### ISSUE TITLE
Checkbox is showing - Error: input is a self-closing tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

### ISSUE THREAD

**Issue by mayankpatel-mit** [atomostechhq/genesis#25]
While using the Checkbox component, I found that there is a specific error. Please find below the error screenshot and the logs.

<img width="1411" alt="Screenshot 2024-05-02 at 6 44 57 PM" src="https://github.com/atomostechhq/genesis/assets/53487115/ef7f66db-397f-419f-a368-550292843776">

>  ⨯ Internal error: Error: input is a self-closing tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

PFB the code for the file

```
"use client"
import { Button, Chip, Checkbox } from '@atomos_tech/genesis';
import '@atomos_tech/genesis/style'

export default function Home() {
  return (
    <>
    <div className='theme-brand'>
      <Button variant={"filled"} intent={"primary"}>
          Primary
      </Button>
      <Chip intent={"primary"} size={"lg"}>My name is khan</Chip>
      <Checkbox>Testing</Checkbox>
    </div>

    </>
  );
}
```

**Comment by riyavish13** [comment]
I have fixed this issue
